export const formsConfig = {
    emailRegexp: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    incorrectEmailMsg: 'Incorrect email',
    noPassworsMsg: 'Password must not be empty',
    shortPasswordMsg: 'Password must be at least 6 symbol long',
    passwordNotConfirmedMsg: 'Passwords are not equal',
    passwordMinLength: 6,
    passwordMaxLength: 32,
    incorrectPasswordMsg: 'Password must contain at least one digit and one latin letter',
    ingredientsNameRequired: 'Name is required',
    recipeNameRequired: 'Name is required',
    ingredientsPriceRequired: 'Price is required',
    ingredientsPricePositive: 'Price must be positive',
    recipeErrorMsg: 'Recipe must have name and ingredients',
    maxIngredientsPerRecipe: 10,
    quantityMustBeNumber: 'quantity must be number',
};
